# Generated by Django 2.0.4 on 2018-05-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('strategies', models.CharField(max_length=1000)),
                ('stock_count', models.CharField(max_length=1500)),
            ],
        ),
    ]
