# Generated by Django 2.0.4 on 2018-05-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestMain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
		('lookup', models.CharField(max_length=100)),
                ('number_of_stocks_1', models.IntegerField()),
                ('number_of_stocks_2', models.IntegerField()),
                ('number_of_stocks_3', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
